{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aimrank.nginx" . }}
data:
  nginx.conf: |
    events {

    }

    http {
      map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
      }
      
      server {
        listen 80;
        listen [::]:80;
        server_name localhost;
        return 301 https://localhost$request_uri;
      }
      
      server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name localhost;
        
        ssl_certificate /etc/nginx/certs/aimrank.crt;
        ssl_certificate_key /etc/nginx/certs/aimrank.key;
        
        location / {
          proxy_pass http://{{ .Release.Name }}-aimrank-web;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection keep-alive;
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /graphql {
          proxy_pass http://{{ .Release.Name }}-aimrank-web;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
        }
      }
    }
  aimrank.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDuTCCAqGgAwIBAgIUR8UZtkC/KE8LcowlGQoD9vEn5t0wDQYJKoZIhvcNAQEL
    BQAwbDELMAkGA1UEBhMCUEwxDzANBgNVBAgMBktyYWtvdzEPMA0GA1UEBwwGS3Jh
    a293MRAwDgYDVQQKDAdBaW1yYW5rMRAwDgYDVQQLDAdBaW1yYW5rMRcwFQYDVQQD
    DA5kZXYuYWltcmFuay5wbDAeFw0yMTA1MjkxMTM3MzRaFw0yMjA1MjkxMTM3MzRa
    MGwxCzAJBgNVBAYTAlBMMQ8wDQYDVQQIDAZLcmFrb3cxDzANBgNVBAcMBktyYWtv
    dzEQMA4GA1UECgwHQWltcmFuazEQMA4GA1UECwwHQWltcmFuazEXMBUGA1UEAwwO
    ZGV2LmFpbXJhbmsucGwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8
    SA7S1nMUqvd7OWiaHeXYRZi5nUS1MPQqFPoEzV/b7F/Xh39klHQjLNbVbs80GKzk
    85cgn02ChycppSJ+gIOrlCJ0Eys4msuKBbU1Y8KeNR9fO2lFGer0v41oXGL8IjMC
    Xp4a5YIY+CfQGBca7/MKu6JGk60Xk1Swtk0UiIkhDY0oStverQ76Jtvrdyqzeh4q
    J0giEGGx5LTxWp3sZVz758YzW2dDNp75lkk6gYP+Ydfu4Iyqw1vmuCCFygkB3bOI
    ptaJvbLN2+dqusfsra9uWJmrKvDVYq6dKFbTO+IHJ6GOPfmo3tRqFKdvqB0zvB5g
    XMmVK/O9FaCyhf5NyE4HAgMBAAGjUzBRMB0GA1UdDgQWBBTpyE/dxd5g6k7D7c9d
    Hma9EFR9bTAfBgNVHSMEGDAWgBTpyE/dxd5g6k7D7c9dHma9EFR9bTAPBgNVHRMB
    Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQA2Zx50iZ+DEWR0fdX/VKx7isgo
    Y6i4rwCOHg7WK4679usOMbyjmBK5RVYHijeZU8QVkXrIrbULaV5KpZpoE50oF4MN
    qAnbBTfGoHkzdAV+8QcXly7a9EDW0NkRYDA0cpKBimDi+qiEy7jPMHdLQ9pFabkx
    d8d9ejtI6VtGp4k0SzFpJwGdcSytEzccplZi4OKpbm1wMBmYCZo72+ghchyZ14xl
    gcuvcuFVK3i8lNgZ3IlOovV9sTghDxXV1haYmOZyJHB/mapN3PznD6W4HBluhFsy
    rQ9a/qCb8bCWnwQa2ysyCU5cMFltHgNRKJcfcMvKmyxa/YZawLQO5S57T7jL
    -----END CERTIFICATE-----
  aimrank.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC8SA7S1nMUqvd7
    OWiaHeXYRZi5nUS1MPQqFPoEzV/b7F/Xh39klHQjLNbVbs80GKzk85cgn02Chycp
    pSJ+gIOrlCJ0Eys4msuKBbU1Y8KeNR9fO2lFGer0v41oXGL8IjMCXp4a5YIY+CfQ
    GBca7/MKu6JGk60Xk1Swtk0UiIkhDY0oStverQ76Jtvrdyqzeh4qJ0giEGGx5LTx
    Wp3sZVz758YzW2dDNp75lkk6gYP+Ydfu4Iyqw1vmuCCFygkB3bOIptaJvbLN2+dq
    usfsra9uWJmrKvDVYq6dKFbTO+IHJ6GOPfmo3tRqFKdvqB0zvB5gXMmVK/O9FaCy
    hf5NyE4HAgMBAAECggEAEJRb0c8WhSxk7JHqlx+o3LmMMFQb98Sey5HbTk7zcP9I
    lUcWPbog2/QX2uWOE21U1DhrB3Fftu3F0hH7jp4sehBqVERX2v0ujTHhehkVyy6s
    W4t0wqP8n566igUQplkwmrXQQFgTc7VudBGa/0E/6qMJMCPS6y+LFqCG+xbm1GUh
    SPhvL/Zp5K0RTuQ3Dog0nNOLIP65u53JJSz7goicfGzJJMHczL4bGPysg0K34/cu
    FhJO3lCsccE61XXj9cK6OtdGgjGEu8sRG//MF1FJ50m+hI21HtUIwTVgkjyB15ZK
    VENMm98MsVthlkzk6L4jgoBe2H0UGZUjyEG1gqttCQKBgQDvQbDP3RRvmX5KJt7y
    v/b+odkOnyVEUZigDNoC2DTC7HoNfJEQF1Eqh4jxoKuQT/YWAmLBFZz7ZpxqUCNF
    mpGKnqtKqsgChXKSyNBSfGBM5+JCqXWbemLoJJuWCGFD45OA0uJLKA1ug8HMMk3e
    HZsNmqxOOaQpE88wL4NTCa+2TQKBgQDJdSRagV6x9deMDB+mry/Dy4xJMNwACgnz
    qzpxUD9fakPo0fuOGzii7i5HgFGTY/AUjggzRJzqtNJynnxWNJBXVVrnf1GmScBH
    rS/3aFhU+E4R4Ymb88RlW0+XPpXEmD0kY6GNzXE+2FjY8nOzGm4QFBQN1vFMHjJf
    amnQ0menowKBgAvH5Ufm7+mq2jAWh+XWE/hnycNRjMk3Z1eCKn33XWm3sS7W0mHD
    dCiu8cxMCAacGVbuGSS+xrMOU2dcuM/lk4MK2w5bKGwPXBvkLXXST/+Zb2eu5m6Y
    cSRTISIbGYb5PrsaJzBiMX8el71RQMpOFONvmUpkxjOLmSkbPdEp6fAFAoGAJvM2
    HyWKKIAut44UhIa0hneRXQlMT9mhCPKfLw9j4U/LZ3VJ3LTYo2/HlN1zaDrXTTIU
    1cy7RgnF8pE/2u74xVnkZIPSRoNV4MXUU1JiWbNUbNKdZ4CfBTW9UrGwBT2l/KYi
    syb4cT0lGHTv973xb7xiEDbxmlTwSlBpuw0jK18CgYBsGhbqNHOWFU77sNhG4eKn
    XcR3oPJQyqgRxGmcyUn8au6XydAPbMYpjUy4wUMJjCST4K9hhYh+rBujMIum1Xa/
    b5DdTBmCKsnW6X/XZlklSQwg9n5tOLg8E+ej7j4vk9WclPvKJ7I10W7KC6Xz+A3G
    HD7fmHlidYwSe88zrr1kiA==
    -----END PRIVATE KEY-----
{{- end  }}