apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aimrank.rabbitmq" . }}
data:
  user: {{ .Values.rabbitmq.credentials.username | quote }}
  pass: {{ .Values.rabbitmq.credentials.password | quote }}