apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimrank.rabbitmq" . }}
spec:
  selector: {{ include "aimrank.rabbitmq.labels" . | nindent 4 }}
  ports:
  - name: management
    port: 15672
    protocol: TCP
  - name: prometheus
    port: 15692
    protocol: TCP
  - name: amqp
    port: 5672
    protocol: TCP
