apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aimrank-agones-cluster.fullname" . }}-secret
data:
  {{- $host := include "aimrank-agones-cluster.postgres" . }}
  {{- $database := .Values.postgres.database }}
  {{- $username := .Values.postgres.username }}
  {{- $password := .Values.postgres.password | b64dec }}
  connectionString: {{ printf "Host=%s;Database=%s;Username=%s;Password=%s" $host $database $username $password | b64enc }}