apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aimrank.postgres" . }}
stringData:
  username: {{ .Values.postgres.credentials.username | quote }}
data:
  password: {{ .Values.postgres.credentials.password | quote }}
