version: "3.5"

services:
  pod:
    image: mariuszba/aimrank-pod:latest
    depends_on:
      - web

  web:
    image: mariuszba/aimrank-web:latest
    ports:
      - 80:80
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.0.10-alpine

  rabbitmq:
    image: rabbitmq:3.8.9-management
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5

  db:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
