version: "3.5"

services:
  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=aimrank
    ports:
      - 5432:5432
    volumes:
      - ../postgres:/docker-entrypoint-initdb.d
        
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
