version: "3.5"

services:
  nginx:
    image: nginx:1.19
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    restart: always
    
  web:
    image: ghcr.io/aimrank/aimrank-web:local
    build:
      context: ../Aimrank.Web
      dockerfile: Dockerfile
    volumes:
      - ../Aimrank.Web/src/Aimrank.Web.App/wwwroot:/app/wwwroot
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    command: [ "sh", "-c", "dotnet Aimrank.Web.Database.Migrator.dll && dotnet Aimrank.Web.App.dll" ]

  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=aimrank
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aimrank" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
