version: "3.5"

services:
  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=aimrank
    ports:
      - 5432:5432
    volumes:
      - ../postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aimrank" ]
      interval: 5s
      timeout: 5s
      retries: 5
        
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
