version: "3.5"

services:
  cluster:
    image: mariuszba/aimrank-cluster:latest

  pod:
    image: mariuszba/aimrank-pod:latest
    ports:
      - 27016-27019:27016-27019/udp
      - 27016-27019:27016-27019/tcp
    depends_on:
      - cluster

  web:
    image: mariuszba/aimrank-web:latest
    ports:
      - 80:80
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.0.10-alpine

  rabbitmq:
    image: rabbitmq:3.8.9-management
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
