version: "3.5"

services:
  cluster:
    build:
      context: ../Aimrank.Cluster
      dockerfile: Dockerfile

  pod:
    build:
      context: ../Aimrank.Pod
      dockerfile: Dockerfile
    volumes:
      - ../Aimrank.Pod/container_data:/home/steam/csgo

  web:
    build:
      context: ../Aimrank.Web
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Database=Host=db;Database=aimrank;Username=aimrank;Password=aimrank
    volumes:
      - ../Aimrank.Web/src/Aimrank.Web.App/wwwroot:/app/wwwroot
  
  redis:
    ports:
      - 6379:6379

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672

  db:
    environment:
      - POSTGRES_PASSWORD=aimrank
      - POSTGRES_USER=aimrank
    ports:
      - 5432:5432
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
