name: Deploy

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup kubectl and helm
        uses: ./.github/actions/kubectl
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
      - name: Upgrade or install chart
        shell: bash
        env:
          EMAIL_SERVICE_USERNAME: ${{ secrets.EMAIL_SERVICE_USERNAME }}
          EMAIL_SERVICE_PASSWORD: ${{ secrets.EMAIL_SERVICE_PASSWORD }}
        run: |
          helm upgrade aimrank-live ./charts/aimrank \
            --install \
            --namespace aimrank \
            --set aimrank-web.emailService.username=$EMAIL_SERVICE_USERNAME \
            --set aimrank-web.emailService.password=$EMAIL_SERVICE_PASSWORD